# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock          # command run when invoking loginctl lock-session
    unlock_cmd = pkill -USR1 hyprlock             # command run when unlocking the session
    before_sleep_cmd = loginctl lock-session      # lock before suspend/hybernation
    after_sleep_cmd = hyprctl dispatch dpms on    # ensure display turns on after waking up
    ignore_dbus_inhibit = false                   # whether to ignore dbus-sent idle-inhibit requests (like Firefox/Steam)
    ignore_systemd_inhibit = false                # whether to ignore systemd-inhibit requests
}

# STEP 1: Dim the screen (150 seconds / 2.5 minutes)
listener {
    timeout = 150                                 # 2.5 min
    on-timeout = brightnessctl set 10%            # set monitor backlight to 10%
    on-resume = brightnessctl set 100%            # reset monitor backlight to 100%
}

# STEP 2: Turn off keyboard backlight (150 seconds / 2.5 minutes)
listener {
    timeout = 150                                 # 2.5 min
    on-timeout = brightnessctl -d *kbd_backlight* set 0 # turn off keyboard backlight
    on-resume = brightnessctl -d *kbd_backlight* set 3  # turn keyboard backlight back on
}

# STEP 3: Lock the screen (300 seconds / 5 minutes)
listener {
    timeout = 300                                 # 5 min
    on-timeout = loginctl lock-session            # lock screen via hyprlock
}

# STEP 4: Turn off the display (330 seconds / 5.5 minutes)
listener {
    timeout = 330                                 # 5.5 min
    on-timeout = hyprctl dispatch dpms off        # screen off
    on-resume = hyprctl dispatch dpms on          # screen on
}

# STEP 5: Suspend the system (600 seconds / 10 minutes)
listener {
    timeout = 600                                 # 10 min
    on-timeout = systemctl suspend                # suspend pc
}
