-- Generated by nwg-displays on 2026-07-18 at 14:45:28. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1366x768@60.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100.0",
    position = "1366x0",
    scale = 1.0
})
