hl.on("hyprland.start", function()
	hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
	hl.exec_cmd("waybar")
	hl.exec_cmd("mako")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("$HOME/.config/scripts/random-wallpaper.sh")
	hl.exec_cmd("$HOME/.config/hypr/scripts/hypr-colors.sh")
	hl.exec_cmd("$HOME/.config/scripts/battery_tracker.sh")
	hl.exec_cmd("$HOME/.config/scripts/wlsunset.sh")
	hl.exec_cmd("$HOME/.config/scripts/media-notify.sh")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XAUTHORITY")
end)
